services:
  - type: web
    name: mcp-demo
    runtime: node
    plan: starter
    region: oregon
    buildCommand: bun install
    startCommand: bun run start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_DOMAINS
        value: mcp.demo.cjav.dev
      - key: SERVER_TOKEN
        generateValue: true
    domains:
      - mcp.demo.cjav.dev
    healthCheckPath: /health
