services:
  - type: web
    name: mcp-demo
    plan: starter
    region: oregon
    buildCommand: bun install
    startCommand: bun start
    envVars:
      - key: NODE_ENV
        value: production
      - key: ALLOWED_DOMAINS
        value: mcp.demo.cjav.dev
    domains:
      - mcp.demo.cjav.dev
